config/routes.rb
SearchDie::Application.routes.draw do
  
  resources :search_contents
  
  root to: 'search_contents#search_page'
  
  match '/history', to: 'search_contents#history_page'
  match '/results', to: 'search_contents#results_page'
  match '/show_results', to: 'search_contents#show_results_page'
  match '/store_history', to: 'search_contents#store_history'
  match '/delete_all', to: 'search_contents#delete_all'
  

end

app/models/search_content.rb
class SearchContent < ActiveRecord::Base
  attr_accessible :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/search_contents_controller.rb
class SearchContentsController < ApplicationController
 $content=""
  def search_page
    @search_content=SearchContent.new
  end
  
  def store_history
    @search_content=SearchContent.new(params[:search_content])
    if @search_content.save
      redirect_to results_path, :notice => "Your Search has been Saved"
      $content=@search_content
    else
      render "search_page"
    end
  end
  
  def history_page
    @search_contents=SearchContent.all    
  end
  
  def results_page
    require 'oauth'
    require 'json'
    api_key = "3ny3q0g0dq0m"
    api_secret="0uofVVUTKxWO7jim"
    user_token="83a65c8f-ae45-4cdb-8ebe-09d6c55c4c1f"
    user_secret="c9dc334a-348c-49a4-9eb7-33a862894332"
    
    # Specify LinkedIn API endpoint
    consumer_options = { :site => "https://api.linkedin.com",
                     :authorize_path => "/uas/oauth/requestToken",
                     :request_token_path => "/uas/oauth/accessToken",
                     :access_token_path => "/uas/oauth/authorize" }
    
    # Use your API key and secret to instantiate consumer object
    consumer = OAuth::Consumer.new(api_key, api_secret, consumer_options)
    
    # Use your developer token and secret to instantiate access token object
    access_token = OAuth::AccessToken.new(consumer, user_token, user_secret)
    @search=$content.content
    # Make a request for JSON data
    @json_txt = access_token.get("/v1/people-search?keywords=#{@search}", 'x-li-format' => 'json').body
    @profile = JSON.parse(@json_txt)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_contents_helper.rb
module SearchContentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SearchDie</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1><%= link_to "Search Page",root_path%></h1>

<% flash.each do |key, value| %>
	<p><%= value %></p>
<%end%>

<%= yield %>

</body>
</html>

app/views/search_contents/history_page.html.erb
<hr />
<h3>Search History</h3>
<hr />
<%@search_contents.each do |search_content|%>

	<h3><%= search_content.content%></h3>
	

<%end%>

app/views/search_contents/results_page.html.erb
<h3>Results Page</h3>
<hr />
<%=  @search%>
<hr />
<%=  @profile%>
<hr />
<%$i=0 %>
<%$num= @profile["people"]["_count"].to_i%>

<%while $i< $num do %>
	<%first = @profile["people"]["values"][$i]["firstName"]%>
	<%last = @profile["people"]["values"][$i]["lastName"]%>
	<%= @profile["people"]["values"][$i]["id"]%>
	<% $i +=1 %>
	<h2><%= link_to "#{first} #{last}",show_results_path%></h2>
	<hr/>
<%end%>

app/views/search_contents/search_page.html.erb
<hr />
<h3>Search Page</h3>
<hr />
<%= form_for @search_content, :url=>{:action => "store_history"} do |f|%>
	<%= f.label "Search"%><br />
	<%= f.text_field :content%>
	<%= f.submit "SEARCH!!!"%>
<%end%>

<small><%= link_to "Search history", history_path%></small>

app/views/search_contents/show_results_page.html.erb
<h3>Show Result Page</h3>